name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  get-changed:
    # check for any changes to an app VERSION file
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.mapped-files.outputs.matrix }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/VERSION
          json: true
          write_output_files: true
      -
        name: Map to JSON
        # Get the parent folder and add to an array
        id: mapped-files
        run: |
          set -eux
          DATA=$(echo ${{ steps.changed-files.outputs.all_changed_files }} | jq -c '. | map(split("/")[0]) | unique')
          echo "matrix=$DATA" >> "$GITHUB_OUTPUT"
  run-matrix:
    needs: get-changed
    # Skip if no changes in app versions in this push
    if: needs.get-changed.outputs.matrix != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: ${{ fromJSON(needs.get-changed.outputs.matrix) }}
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Get version number
        # Read the version number out of app/VERSION and push to ENV
        env:
          CTX: ${{ matrix.versions }}
        run: |
          VER=$(cat ${CTX}/VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV    
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        # TODO: other repos
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        # Build docker image using the app folder context.
        # Tag with appname and version string
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:${{ matrix.versions }}"
          push: true
          tags: |
            paulkm/${{ matrix.versions }}:${{ env.VERSION }}
            paulkm/${{ matrix.versions }}:latest

